### ISSUE TITLE
Why? What? When? Where? How?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/aguid-elixir#1]
Porting the Node.js module https://github.com/dwyl/aguid over to Elixir 
for use as primary key in https://github.com/dwyl/alog 

+ [ ] `aguid/0` generates a ***pseudorandom*** UUID (_always different_) that conforms to spec: https://en.wikipedia.org/wiki/Universally_unique_identifier
  ![image](https://user-images.githubusercontent.com/194400/47866459-b4cfa300-ddf6-11e8-901e-fb7dd2a41ac4.png)
  + [ ] https://github.com/zyro/elixir-uuid

+ [ ] `aguid/1` accepts a string or JSON (map) which is used to generate the _deterministic_ UUID.
This should always be the same and irreversible. 
+ [ ] `aguid/2` accepts the String or JSON (map) as `aguid/1` but also accpets a "parent" UUID which should be referenced in the "child" UUID such that we can "lookup" the parent or "chain" of nodes.

**Comment by nelsonic** [comment]
"on hold" while we discuss the more **_fundamental_ question: _should_ we use UUIDs**? https://github.com/dwyl/alog/issues/15

**Comment by nelsonic** [comment]
Closing in favour of: https://github.com/dwyl/cid/issues/1
